#-------------------------------
# General Site Settings
title: ACORD Blog
logo: acordminimallogo.PNG # You can add own logo.
description: Software Development Company


#-------------------------------
# Author Settings
author:
  name: ACORD Robotics
  image: retrieval_team_by_macrebisz_dbfocxw-pre.jpg
  say-hello: Hello, we're the ACORD Team
  bio: A software, scientific engineering and writing organization based in Australia. Est. 2015 as Alliance of Droids, renamed to ACoRD Robotics in 2019. # Liam's bio: Designs, talks, and writes about <strong>web design</strong>, <strong>development</strong>, <strong>science</strong>, and gaming. I, along with my team at ACORD, will keep you updated with what's going on.


#-------------------------------
# Contact links
twitter: https://twitter.com/OpusTheRobot # Add your Twitter handle
facebook: https://facebook.com/Droidology # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/droidology # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: acordrobotics # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: droidology # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
